"""change consumo type int to float

Revision ID: 48ab09b81ca7
Revises: 51c6957b2dc2
Create Date: 2021-11-11 23:45:58.857869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48ab09b81ca7'
down_revision = '51c6957b2dc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehiculo', 'vehiculo_combustible_consumido',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehiculo', 'vehiculo_combustible_consumido',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
